### PR TITLE
Numerous Fixes

### PR DESCRIPTION
**Pull request by Millicant**
Basic re-structuring

### CODE REVIEW

**Comment by Millicant** [comment]
Hey @capitaladot any chance this can be merged?  You're more of an expert on conflict resolution than I am.  If not, let me know and I'll have to re-write these changes into the current file (which will be a huge pain in the butt).

**Comment by Millicant** [comment]
This has conflicts - I'm having to go through the master and update it all again manually.

**Comment by amis92** [comment]
@Millicant if you do not plan to use that branch again, please delete it, so it won't use up available branch names in future ;)

**Comment by Millicant** [comment]
@amis92 you got it!

**Pull request closed without merging**
