### PR TITLE
Remove linked rules bloat

### PR DESCRIPTION
**Pull request by capitaladot**
- move linked rules over to LA category from test category
- remove linked rules, previously under LA units, now under LA category
- add LA rule link to LA category

### CODE REVIEW

**Comment by capitaladot** [comment]
I think rules text under units is just a "nice to have" since we now get a
listing of rule names under units.

Let's go ahead with this and depend on Jon Taylor to add the feature to
display rules text under units for more than root level Categories.

On Dec 14, 2017 6:22 AM, "zopha" <notifications@github.com> wrote:

*@zopha* commented on this pull request.

A quick test earlier had the rules appear in the Rules Summary section but
nothing appeared in the units. I'm not sure but the selection of LA needs
to be moved from the SSE to the root entry to get them to show up.

I'll try to test later today to confirm this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/horus-heresy/pull/1205#pullrequestreview-83471940>,
or mute the thread

**Comment by zopha** [comment]
Sorry, I didn't word it right.

"since we now get a listing of rule names under units."

That's what I was saying was missing, although that's just from 5 - 10 minute testing on 2.01.06 so 07 may have fixed it or it was just the unit I was looking at.

**Comment by zopha** [comment]
Okay, I can see it's working now! Either it was .06 or I was using the wrong files.

https://i.imgur.com/Hy4UNxA.png

Was the Troops Walk rule added with this?

**Comment by zopha** [comment]
Ignore the troops walk thing, I was looking at v500 instead of v501. 501 looks good, there are still rules on some units Tactical Squad and Breacher squad for example. Is this intended or can they be removed as well?

image of rules on tactical squad

**Comment by capitaladot** [comment]
Cool, not intended, can be removed as well.

**Pull request merged**
