### PR TITLE
Omni fix of things and stuff

### PR DESCRIPTION
**Pull request by Mayegelt**
Added Venerable Ancient to have Warlord Traits

Many units added missing Hexagrammaton
Praetor Armoured Assault Transport
Marauder Destroyer
Marauder Bomber
Legion Crassus Armoured Assault Transport
Macharius Omega Heavy Tank
Legion Macharius Omega Heavy Tank
Malcador
Minotaur
Caestus Assault Ram
Land Raider Achilles Squadron
Land Raider Phobos Squadron
Primaris-Lightning Strike Fighter
Avenger Strike Fighter
Thunderbolt
Spartha Attack Bike Squad
Legion Deathstorm Drop Pod
Castra Ferrum Dreadnought Talon
Rapier Battery
Cerberu

Forge Lord Machinator Array was only linked to the profile not SE, which meant it was missing 2 weapons and a special rule.

Nightlords Contekar Dedicated Transports added
Sire of Nightlords buffs apply to all Infanty/Cavalry/Dreads

Assault cannons for Levi are 20pts upgrade from flamers EACH, which means you can take 1 or 2 on a levi. New option added for 1 heavy flamer and 1 assault cannon.

Command Squads and Centurion and Praetor now have access to Inferno Pistols as a replacement to Plasma Pistols for BA.

Grav Pistols (and a couple more Infernos) added to units including centurion

Contemptor Invaendius profile was missing

Gorgon Termy Armour upgrade for Cata cost

Contemptor Incaendius profile

Kharn compulsory HQ

Infravisor on Centurions and Praetors

Replaced (Collective) version of Ravens Talons from Command squad, as otherwise If you give one member of the legion command squad Ravens Talons it automatically gives all chosen the talons.

RG
Meltabombs have now have proper costs for Dark Furies choosers of the slain. If one takes they all do.
Raven's Talons Collective was given Barricade Subtype for some unknown reason, this is removed.
Deliverers heavy weapon of Multi melta should have been 25pts instead of 10.

AL
Armour Spearhead Land Raider for Headhunters

Power Daggers and Venom Spheres on all characters in RoT units
Crimson Paladins,
Dawnbreakers
Angels Tears
Interemptor Squad
Inner Circle Cenobuim (and broken claws) all models
Grave Wardens
Mortus Poisoner
Kakophoni
Palatine Blade & Aquilae
Phoenix Termy
Sun Killer
Huscarl
Phalanx Warder
Templar Brethren
Gorgon Termy
Medusan Immortals
Iron Havocs
Tyrant Siege Termy
Atramentar
Contekar
Night Raptor
Terror Squad
Dark Furies
Deliverers
Mor Deythan
Firedrakes
Pyroclast
Reaver Aggressor and Reaver Attack squads
Gray Stalkers
Gray Slayers
Jorlund Hunter
Varagyr Wolf Guard
Ammitara Occult
Khenetai
Numerologist
Sekhmet
Fulmentarus
Invictarus Suzerain (looks a bit messy due to currently all collectives. Might be able to be tidy up later or make it more accurate without making it more of a mess.)
Locutarus
Nemesis Destroyer
Praetorian Breacher
Dark Sons of Death
Falcon's Claws
Golden Keshig
Ashen Circle
Rampager
Red Butchers
Red Hand Destroyers

IF
The rules for dorns weapons or wargear have not been added only his warlord trait
Castellan consul lacked pts on the weapon upgrades, and also was available to termy centurions and shouldn't have been.

IW
Fix for Perty getting Dominator and Iron Circle as Primarchs Retinues.

IF/BH
Removed Assault Cannon option from Javalin (shouldn't have had it as its not infantry, dreadnought or vehicle)

UM
Added collective bolt pistols and chainswords to nemisis destroyers as it was missing.

TS
Thosand Sons Æther-fire magna-cannon on Dreads

Proteus landspeeder hunter killers PTS are wrong

SAL
Nullificators get optoins for Dragonscale Storm Shield instead of combi bolter.

IF
Preator and Centurion in temy armour didnt get access to storm shields as swap for combi bolters.
Sigismund is in the detachment Templar brethren become troops.

Thallax now available for all legions if Forgelord is taken.

Needs Banestrike:
Centurion in may take. Termy Cent needed to include AL as well as SoH
Praetor in may take. Termy Praetor needed pts added and rework of limitation to include AL and points cost added.

WB
Warpfire weapons on some characters, and units as well as dreads (Pistols, Blasters & Cannons)
Dark Channeling on Centurions, Preator, Techs and Apoth, as welll as some others like Terminators and a couple of other missed units.
Burning Lore on Preators

Consul Praevian hasn't got their option to take Castellax or Vorax companions

Tainted weapons moved to be like the EC and other ones inside power weapons SEG rather than diving 2 levels into power weapons to select.

Master of Armour pts were wrong

Toxin Bombs on Tech Marines was missing

Iron Havoc Segeant wrong A and LD as it seemed to be a direct copy from normal one.

Reavers Chainaxes were hidden by accident

### CODE REVIEW

**Comment by Mayegelt** [comment]
Things to do that have been noted, currently reported on FB but not checked.

WB
Heavy support squads don’t seem to have the warpfire cannon option for WB
Dark Channeling on Centurions, Preator, Techs and Apoth.
Tainted blade for a unit sergeant, burning lore or warpfire pistol on a praetor.
"from what i could find: pistols missing for preators, centurions (and all consuls), command squads, as special weapons for both destroyer versions, techmarines.
Blasters missing for: techmarines, terminators special weapon.
Cannons: armitos, sky hunter jetbikes, proteus speeder, heavy support squad"

NL
Regarding the headsman axe I think that should be fixed only on terror squad's headsman and night raptor's huntmaster. In the current version they can take the axe for 15 points, but technically they should first take a power weapom and then upgrade for 15 more points, as, for example, the pretor and the assault squad sergent , where this works correctly.

TS
Check the options for the Contemptor, it does not add the 1000 son special plasma gun type when you select the plasma cannon.

IF
Many termys might not be getting access to storm shields

AL (& maybe SoH)
Needs Banestrike:
Centurion (including all non-terminator consuls)
Praetor (including both terminator varieties)
Cataphractii and Tartaros Centurions have an option for it (but it’s free when it should be 5 points) when no Rewards of Treachery is selected or one of the other legions is selected, but the option disappears when Alpha Legion is selected as their own Reward of Treachery (I use this option when I don’t want to select another legion’s unit so it doesn’t clutter my list building).

**Comment by Chaosmasters** [comment]
"Deliverers heavy weapon of Multi melta should have been 25pts instead of 10."

This one needs to be done carefully, as the Base Deliverer is costed differently for Heavy Weapons option (I don't know why) and has Flamer listed for +5 (which ends up being correct), the Melta as 10 (to total 15, which is one of the obvious errors) and the auto cannon at 20 (To total to 25.. when it is really a 15 point upgrade)

**Comment by Mayegelt** [comment]
I'll recheck the stuff. If it's wonky I'll redo. Not sure why the base cost would have been set wrong

**Comment by Mayegelt** [comment]
Just checked, it looks like the base cost of a Deliverer is 40pts. To upgrade to a flamer is 10, Autocannon 15, Multimelta 25. These are correct.
The issue you were saying was actually the special weapon one was showing as a start of 45pts, as it actually had the flamer cost wrong. It was being charged at 5pts (so 40pts base + 5pts = 45pts) instead of the 10pts it should have cost to make it 50pts base (40 + 10)

**Comment by Chaosmasters** [comment]
> Just checked, it looks like the base cost of a Deliverer is 40pts. To upgrade to a flamer is 10, Autocannon 15, Multimelta 25. These are correct.
> The issue you were saying was actually the special weapon one was showing as a start of 45pts, as it actually had the flamer cost wrong. It was being charged at 5pts (so 40pts base + 5pts = 45pts) instead of the 10pts it should have cost to make it 50pts base (40 + 10)

Yes, sorry… I noticed that when I got back to my phone

**Pull request merged**
