### PR TITLE
Iron Hands Updates

### LINKED ISSUE #2209: Missing IH specific options on some vehicles
**Describe the bug**
Iron Hands specific options for vehicles are present on some but not all vehicles (Blessed Auto-simulacra and Armatus Necrotechnika)

**Expected behavior**
Vehicles concerned : 

- Kratos
- Land Raider Proteus Explorator
- Land Raider Proteus Carrier
- Land Raider Spartan
- Scorpius 
- Vindicator

**Device and data (please complete the following information):**

    OS: Windows
    BattleScribe version 2.03.21
    Release version v16.1.2

### PR DESCRIPTION
**Pull request by figjam-bohica**
## Added Units
Added Deathstorm Drop Pod
Added Iron-Father Autek Mor
Added Shadrak Meduson

## Fixed Units
IH squads and characters moved over to LA - Iron Hands.cat
Assigned Armatus Necrotechnika and Blessed Auto-Simulacra as appropriate

### Related Issues

* closes #2209 and #2204 

## Not done yet

_Any issues related to your new changes, or known missing options_

## Test Case

Please upload a roster do demonstrate your changes.

### CODE REVIEW

**Review by UrsinePatriarch — CHANGES_REQUESTED** [review]
Seems like the WLT of Autek Mor is on multiple lines; you can also remove "Warlord" from the name since we know what it is by the title.

Did you delete the files you moved over into the IH file from the main LA cat?

**Comment by figjam-bohica** [comment]
@UrsinePatriarch I did not delete the units from the LA.cat because it created a broken link in the "Root Selection Entries"  section. Do I just delete the entry from that table or relink to the unit in the IH file? 

Removed the duplicate Warlord. It is formatted similar to others in the LA file now.

**Comment by UrsinePatriarch** [comment]
Since we're moving everything to the new catalogs, you have to delete the LA RSEs and then add new root entries in the new IH catalog; this allows the IH catalog to still reference them without having all non-IH catalogs still load their data.

**Review by UrsinePatriarch — APPROVED** [review]
It was pretty good overall, but with some basic fixes on my end (please ask if you have questions), this sure seems like the complete package now.

**Pull request merged**
