### PR TITLE
IW - add missing Tyrant Siege Terminator profile, fix Dominator Cohor…

### PR DESCRIPTION
**Pull request by MateuszRaubo**
## Fixed Units

- Tyrant Siege Terminator Squad
- Dominator Cohort

### CODE REVIEW

**Comment by UrsinePatriarch** [comment]
I see the missing profiles on Tyrants (no idea how long that's been like that), but what did you "fix" with Dominators? I don't believe they can actually legally take Disintegrators, the Alchem flamer correction is good, but I do believe you've switched all of the Combi-weapons back to Collective for some reason.
Please explain.

**Comment by MateuszRaubo** [comment]
Yes, adding disintegrators is my mistake. Next time I will be more scrupulous 🙂. I change all combie-weapons becouse in Data Editor I get 
image

**Comment by UrsinePatriarch** [comment]
Well, there've been some conflicts now because of other work being done on the catalogs, so I'm gonna go into your branch and merge it by hand; this means I'll take all of the work you've done here and bring it manually into the most current version of the catalog.

**Comment by UrsinePatriarch** [comment]
I copied your work into a basic commit to master [to simplify things](https://github.com/BSData/horus-heresy/commit/ec320a538897a0ed53c96242abbb0f48f3691b70); thank you for your work on this.
Please come and see us in the Discord for any further data-related bugs or help you'd like to offer in the future ~

**Pull request closed without merging**
