### PR TITLE
HH9 Errata fixes (mostly)

### PR DESCRIPTION
**Pull request by Mayegelt**
#1894 #1895 #1896 
HH9 Crusade Errata Updates #1894 #1895

Remove Land Raider Proteus option for Deathwing Companion Terminators, replace with Spartan transport option. (Left the Landraiders in, but only if Steel Fist RoW is in, as it would override their DT preferences)

Remove Hatred and add Preferred Enemy (characters) to Firewing Enigmatus Cabal.

Change Dreadwing Interemptors transport parameters to "10 models or less" rather than exactly 10

Add "This counts as a sword for the purposes of the Mastery of The Blade" to Corswain's The Blade's item description.

Remove the Inbuilt option for the Lion to take Deathwing Companions. Instead give him the same check that allows for Deathwing Companions and Deathwing Companion Terminators to be taken in the "Command Squads" section.

Updated rules and restrictions for the Storm of war to reflect changes.

Also fixed Malcadors from Solar and Militia still having the Superheavy Category.

### CODE REVIEW

**Comment by Mayegelt** [comment]
Whole bunch of LoW 25% limitation fixes to include full army roster, not just force.
#1899

**Comment by Mayegelt** [comment]
When I had to fix the termy armour stuff for RoW reason. I accidently messed up Vigil shield costs when wearing cataphactii

**Comment by Mayegelt** [comment]
Fixed issue that Wordbearers were not demanding the additional HQ choice which has to be a Chaplin or Centurion

**Comment by Mayegelt** [comment]
Redid the fix to move the taxis into bodyguard section.

**Comment by SangEntar** [comment]
Reviewed. All good.

**Review by SangEntar — APPROVED** [review]
Reviewed and approved.

**Review by SangEntar — APPROVED** [review]

**Pull request merged**
