### PR TITLE
Termite / Navigator

### PR DESCRIPTION
**Pull request by Mayegelt**
Termite changes for Militia and Solar Aux done.
Change to Armoured Ceremite that had both rule and profile, that was causing issues.
Navigator moved to be HQ from Elite for Solar Aux.

> ⚠️  NOTE: use notes like this to emphasize something about the PR. This could
> include other PRs this PR is built on top of; reasons for why the PR is on hold; 
or anything else you would like > to draw attention to

## Description
_A few sentences describing the overall goals of the pull request.
What is the current behavior of the app? What is the updated/expected behavior
with this PR?_

## Related Issues
* closes # [insert issue name here](insert link here)

## Todos
_Fill out or remove list items as needed_
- [ ] Tests

## Test Case
_Notes This should be a link to test roster file that evidences your change._
It would also be acceptable to upload the file as a comment.

### CODE REVIEW

**Comment by capitaladot** [comment]
What is this Armoured Ceramite thing?

**Comment by Mayegelt** [comment]
Armoured Ceremite had both a Rule and a Profile on the Militia version and no "Max 1 selection in parent"
image

**Comment by Mayegelt** [comment]
Sorry just had to play around a bit there. Noticed that i hadn't uploaded it correctly and had to mess around then renamed them wrong several times over. The 2 files should now be correct.

**Comment by capitaladot** [comment]
@Mayegelt can you post the files you used to show these changes as tests?

Additionally, I see you you jumped the Solar Aux file two versions, from 52 to 54; let's not skip 53.

**Comment by capitaladot** [comment]
@Mayegelt Now you updated to 55! Please go back to 53.

**Comment by Mayegelt** [comment]
Ahh sorry was playing around when making the changes to MaSade and Displacer, going to put the file up again as 53

**Comment by alphalas** [comment]
@capitaladot does it really matter?

**Pull request merged**
