### PR TITLE
Corrected spelling error

### PR DESCRIPTION
**Pull request by eaxexe**
Fixed a small spelling error in the Taghmata list.

### CODE REVIEW

**Comment by zopha** [comment]
Thanks for the pull request! Except it seems to only contain the commit text, no files changed. Can you check please?

**Comment by zopha** [comment]
Hi @eaxexe got a chance to look at what might have happened?

**Comment by eaxexe** [comment]
@zopha Yes, sorry! I had initially used the Github 'upload' function, and either selected the wrong file (likely), or it bugged out somehow. Sorry about that!

Should be fixed in the latest commit :)

**Comment by eaxexe** [comment]
Fixed the rest of the same misspellings :)

**Comment by zopha** [comment]
Thanks @eaxexe ! Sorry I haven't gotten back to you sooner, I'd merge the request but I see it includes the Legions file now. It looks like it will be okay (since it's a spelling correction) but @capitaladot has another request open with some large changes and, unfortunately, the data files don't take well to multiple merges even with small changes. We'll get it sorted soon enough and see if this can be still merged without issue.

**Comment by eaxexe** [comment]
No worries @zopha, we're all busy :)

I can make the changes again, if issues should occur. Isn't gonna take more than a minute or two!

**Pull request merged**
