### PR TITLE
Moving profiles, fixing Cult Arcana and adding special rules

### PR DESCRIPTION
**Pull request by Mayegelt**
Moving profiles, fixing Cult Arcana and adding special rules name modifiers

### CODE REVIEW

**Comment by Mayegelt** [comment]
@nstephenh big old update here. Let me know if I ended up reversing anything in your patch. I shouldn't have as I think it was just adding pts to paired claws and remove the extra one on Tart Sergeants.
Did notice that Ravens Talons might be wrong price on paired though I think as its set to 0. They should be 5pts each more expensive than lightning claws (or 10pts on a pair)

**Comment by nstephenh** [comment]
Looks like you only got half my fix, I also set the points on paired weapons (though I didn't set the raven talons to be 5 pts more).

**Comment by Mayegelt** [comment]
Copied the pts over for the standard points

**Comment by nstephenh** [comment]
Hard to see on my phone, I'll review tonight. Is there a points modifier based on praetor, etc?

**Comment by Mayegelt** [comment]
Yep.
As said. No rush to review. If it's done by tomorrow afternoon then
hopefully I can get to work on next steps.

**Review by nstephenh — APPROVED** [review]

**Pull request merged**
