### PR TITLE
Terror and Allied Detachments

### PR DESCRIPTION
**Pull request by Mayegelt**
Terror Assault Consol fix (no more limitation in book 9)

Allies restrictions added

No allies allowed list:
Onslaught FOC
ROWs:
Fury of the Ancients
Sky Hunter Phalanx
Drop Assault Vanguard
The Long March
Creeping Death
Last of the Serrated Sun
Horror Cult
Headhunter Leviathal
Hammerfall Strikeforce
Company of Bitter Iron
The Awakening Fire
The Guard of the Crimson King
The Eskaton Imperative
The Steel Fist
The Storm of War
The Unbroken Vow
The Seekers Arrow
The Serpents Bane
Ravenwing Protocol
Ironwing Protocol
The Swift Blade.
Chimerae

No Allowed Space Marine Allies
The Head of the Gorgon
3rd Company Elite
Decapitation Strike
The Hammer of Olympia
The Crimson Path
The Coils of the Hydra
Orphans of Betrayal
The Ironfire
Berserker Assault
The Maru Skara
The Dark Brethren
The Blooded Claws

Updated Corax

Updated Inner Circle Knights. Character only has 1 wound now, rather than the 2 that were in the download.

Plasma Incinerator fixes

Added Eskaton - Plasma Incinerator to Recon squads (cos they can get sniper rifles) 
Added a max 1 limit to Plasma Incinerator for Tact Support (forgot before).
Added Steel Fist Predators are only troops when Compulsory, So max 2 generally, Though Castellan and Onslaught is 3 max
Added Termys and Vets for Primarch's Chosen are only troops when Compulsory, So max 2 generally, Though Castellan and Onslaught is 3 max

### CODE REVIEW

**Comment by Mayegelt** [comment]
@capitaladot I've tested this myself and the list in the description is correct as far as I can tell.
However could you test it yourself as well, just to make sure I've not done something unexpected that would require a revert if its gone wrong. Though I didn't encounter that.

**Comment by Mayegelt** [comment]
Plasma Incinerator fixes

Added Eskaton - Plasma Incinerator to Recon squads (cos they can get sniper rifles) 
Added a max 1 limit to Plasma Incinerator for Tact Support (forgot before).

**Comment by Mayegelt** [comment]
Added Steel Fist Predators are only troops when Compulsory, So max 2 generally, Though Castellan and Onslaught is 3 max

**Review by capitaladot — APPROVED** [review]
This is a leap forward!

**Pull request merged**
