### PR TITLE
Move shared profiles to GST

### PR DESCRIPTION
**Pull request by nstephenh**
Instead of #3100 moving the rites of war, we can just not import the LA library into militia. This will fix rites of war from appearing in militia. (#3099 ?)
Keeps @Mayegelt 's fix for: Aetheric Dominion (Whole Army) from the DOTRS appearing when not wanted in armies like Militia. Fixed by turning off Import.

### CODE REVIEW

**Comment by Mayegelt** [comment]
I didn't know why Militia was imported. So assumed there is reason for it.
If there is not then it seems ok to do as you suggested.

**Comment by The4D6** [comment]
It was imported in order to use the same profiles for the land raider and rhino, so that of they were ever updated in the future we would only have to update one thing

**Comment by Mayegelt** [comment]
Fair enough. So I guess either clone those 2 or move to GST or have a shared asset library.

**Comment by nstephenh** [comment]
This PR moves them to the GST, apologies for not communicating that properly.

**Review by The4D6 — APPROVED** [review]
Seems like a reasonable fix, I didn't realise this would casue issues, sorry!

**Pull request merged**
