### PR TITLE
Stomping a few post hibachi

### LINKED ISSUE #1199: Iron Warriors Warsmith - Father of the Brethren of Iron
Father to the Brethren of Iron: *Not a real entry/rule/wargear. Fabricated by Millicant to ensure Battlescribe works correctly with the Brethren of Iron Rite of War.

This artifact is still in.

### LINKED ISSUE #1211: Narik Dreygur Bug
He lacks Master of Cybernetica, and as a Salamanders option can't take his IW Vets...

### LINKED ISSUE #1216: command squad jump packs are 15pts
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.13

**Platform:** Android

**Dropbox:** No

**Description:** The calculations are way off. For instance on a command squad jump packs are 15pts a piece. Yet for my command squad of 5 it calculates it at 100pts. 15 x 5 =75 not 100.

### LINKED ISSUE #1227: Terminator Legion Command Squad - Incorrect cost
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The points values for a Terminator Legion Command Squad seem to be incorrect. When you select what type of Terminator armour they are wearing, it adds +35pts to the squad total even though this has already been factored in by choosing Terminator Legion Command Squad and not Legion Command Squad. Thanks.

### LINKED ISSUE #1230: Rename entries that contain Legion Specific Replacements
E. G., if a Thunderhammer allows a Solarite Power Gauntlet, rename the containing label to include both options.

### LINKED ISSUE #1234: Heavy Support Squad cannot have any selections of Support Squad (hidden)
- [x] Heavy Support Squad cannot have any selections of Support Squad (hidden)
- [x] Main Support Squad entry in GST

There may be more entries like this. It'll be easier to remove/resolve this when existing work has been completed and merged.

It's linked to an entry in the GST, if it wasn't appearing before it's more than likely surfaced due to a background update in Battlescribe. Either way, it's purpose would have been replaced by the category system.

### LINKED ISSUE #1241: Legiones Astartes - Grey Slayers - missing option for Huscarl
Huscarl should have the Grey Slayers' "Any model in the squad ..." option. At the moment it's not possible to take bolter or combat shield, etc.

### LINKED ISSUE #1243: Rename Age of Darkness Detachment
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** There is no option to take a standard primary detachment in the Warhammer 30,000 - The Horus Heresy whereas you can in the books

### LINKED ISSUE #1244: Legiones Astartes Bogus Entry Needs Deleted
- [ ] Anvillus
- [ ] Deathstorm
- [x] Attack Bikes

### LINKED ISSUE #1255: Centurion Combi-weapons
Terminator Centurions seem to be getting a bogus Combi-Weapon option. Likewise, the "can take a" long arm option for Centurions appears to display even when wearing Terminator armour (should be power/artificer only).

### PR DESCRIPTION
**Pull request by capitaladot**
Centurion Combi-weapons Bug - Choice Bug - Cost
closes #1255 opened 2 days ago by capitaladot

Legiones Astartes Bogus Entry Needs Deleted
closes #1244 opened 9 days ago by capitaladot 1 of 3

Rename Age of Darkness Detachment enhancement
closes #1243 opened 9 days ago by BSDataAnon

Legiones Astartes - Grey Slayers - missing option for Huscarl Bug - Choice Legion
closes #1241 opened 11 days ago by mbielsk

Heavy Support Squad cannot have any selections of Support Squad (hidden) Bug - Validation Legion Problem - Battlescribe Bug
closes #1234 opened 22 days ago by zopha 2 of 2

Rename entries that contain Legion Specific Replacements Legion enhancement
closes #1230 opened 23 days ago by capitaladot

Terminator Legion Command Squad - Incorrect cost Bug - Cost Legion
closes #1227 opened 25 days ago by BSDataAnon

command squad jump packs are 15pts Bug - Cost Legion
closes #1216 opened on Jan 8 by BSDataAnon

Narik Dreygur Bug Bug - Choice Bug - Text/Rule/Profile Legion
closes #1211 opened on Dec 30, 2017 by ChapterGrim

Iron Warriors Warsmith - Father of the Brethren of Iron Bug - Text/Rule/Profile Legion
closes #1199 opened on Dec 10, 2017 by archonkain

### CODE REVIEW

**Comment by capitaladot** [comment]
@zopha on Terminator Command Squad, I see now what you mean and have adjusted things for suit. I also sorted out a big mess with the power weapons and combi weapons in the same.

**Comment by capitaladot** [comment]
@zopha The Grey Slayers thing isn't a bug; the Bolt Pistol, Plasma Pistol, and Hand Flamer are each mutually exclusive, but exchanging them is limited to one every five. I guess it would be easier to deal with errors to uncheck the bolt pistol for any replacements.

**Comment by capitaladot** [comment]
In re: 1230, the modifiers are there, and will work... if @Jonskichov fixes the bug wherein you can set name append modifiers, but they don't presently do anything.

**Comment by capitaladot** [comment]
In re: the default options for Centurions, this is a similar problem to the Grey Slayers. We can either:
- have the default entries not show up by default, and provoke no errors
- have the default entries show up, but throw errors when you switch armour
- put everything in selection groups (one melee, one missile) and set a defaults

Because of min1, max1 is basically the only way we have of auto-selecting default options other than using selection groups (which you-know-who hates due to IPhone UI or something).

**Comment by zopha** [comment]
The other force orgs are still named Optional in the new rulebook, unless there's something else that names them not-optional anymore? It wasn't in the leaked FAQ.

Imgur
Also https://youtu.be/6eB2MwyH7So?t=11m13s

**Comment by capitaladot** [comment]
@zopha: maybe we should add a character to the Crusade Force Organization Chart so that it appears at the top of the list and becomes the obvious choice?

**Pull request merged**
