### PR TITLE
Fixes #1843

### LINKED ISSUE #1843: Salamanders Shenanigans
- [x] Missing correct Heavy Flamer link on several vehicles (and even Firedrakes)

- [x] Rhy'tan's Dreadnought Talon choice is absent

### PR DESCRIPTION
**Pull request by capitaladot**
> ⚠️  NOTE: use notes like this to emphasize something about the PR. This could
> include other PRs this PR is built on top of; reasons for why the PR is on hold; 
or anything else you would like > to draw attention to

## Description
_A few sentences describing the overall goals of the pull request.
What is the current behavior of the app? What is the updated/expected behavior
with this PR?_

## Related Issues
* closes # [insert issue name here](insert link here)

## Todos
_Fill out or remove list items as needed_
- [ ] Tests

## Test Case
_Notes This should be a link to test roster file that evidences your change._
It would also be acceptable to upload the file as a comment.

### CODE REVIEW

**Comment by Mayegelt** [comment]
Just downloaded the push and threw it in. Looks like it works in isolation. However looks like you might not have used the latest version of the HH GST file at least or maybe the latest LA file. As all the knights errant and stuff have moved up to GST so they are available to all, as such it is throwing up a load of not unique id errors.

**Comment by Mayegelt** [comment]
Just downloaded the push and threw it in. Looks like it works in isolation. However looks like you might not have used the latest version of the HH GST file at least or maybe the latest LA file. As all the knights errant and stuff have moved up to GST so they are available to all, as such it is throwing up a load of not unique id errors.
Also looks like you are on version 597 of the LA one, and we are up to 611 ATM, so might be a whole heap of missing stuff.

**Review by Mayegelt — CHANGES_REQUESTED** [review]
Looks like you are using old files. Needs an update of HH GST and LA files and put changes back in again (also put this in comments).

**Comment by capitaladot** [comment]
@Mayegelt conflicts rebased and resolved.

**Comment by Mayegelt** [comment]
@capitaladot if it all looks good to you then I'm happy for it to be pushed though, then I might work on the next lot of stuff tomorrow if I can...
ZM or Mournival... or maybe both...

**Pull request merged**
