### PR TITLE
Atramentar and Exemp/Legacy

### PR DESCRIPTION
**Pull request by Toreador13**
Added Atramentar and Exemplary and legacy options

### CODE REVIEW

**Comment by UrsinePatriarch** [comment]
You also seem to have added a button to toggle Exemplary/Expanded units on and off. Can we get screenshots of that in action?
This file will also require a fair bit of manual merging because of the recent commits from other authors, which isn't your fault but will require more time on our parts.

**Comment by Toreador13** [comment]
Yeah, I posted the screenshots on discord. I'm Mr Dark over there. 

And as always merging is fun. This is a nice and simple update, so I can wait until others are done, merge master back in and redo this when needed. Not a big deal.

**Comment by UrsinePatriarch** [comment]
Right, forgot you're Mr. Dark. Yeah, looks good to me.
And no, no need for you to re-do your work; just gimme a day or two so I can manually merge some other parts and then swap your stuff in.

**Review by UrsinePatriarch — DISMISSED** [review]

**Comment by UrsinePatriarch** [comment]
Pushed commits to master.

**Pull request closed without merging**
