### PR TITLE
All Book 8 (without Daemons of the Ruinstorm)

### PR DESCRIPTION
**Pull request by Mayegelt**
Had this linked from my dropbox as i have been patching it, and no issues seem to have been found (or at least some were but have all been resolved as reported).

This is Book 8 with the only exception being that I haven't added Daemons of the Ruinstorm.

### CODE REVIEW

**Comment by capitaladot** [comment]
Most impressive!

I just got my book at Adepticon.

**Comment by Mayegelt** [comment]
It took me long enough. It was about 15+hours of coding it all in. Seems to have had community approval from a lot of people @capitaladot

**Comment by KieranABrown** [comment]
Any chance I can use these before the commit?

**Comment by Mayegelt** [comment]
Yep. Just download my pull request or use my dropbox link to use my most up to date files.

**Comment by thebiggeordiegeek** [comment]
Do you know when this will be available for download?

**Pull request merged**
