### PR TITLE
Fill out Predator Squadron, Add Vulkan

### PR DESCRIPTION
**Pull request by mjfreese**
## Added Units
- Vulkan

## Updated Units
- Predator Squadron
- Some warlord trait references

## Not done yet
- Vulkan only has points and some of his rules and equipment

image

### CODE REVIEW

**Comment by UrsinePatriarch** [comment]
Can you elaborate on the Warlord Issues? There's a very good chance it's the same reference issue that somehow got added to the GST (and has been fixed), but I'd like to be sure.

**Comment by mjfreese** [comment]
> Can you elaborate on the Warlord Issues? There's a very good chance it's the same reference issue that somehow got added to the GST (and has been fixed), but I'd like to be sure.

If you see towards the bottom of the file there are a few places that had warlord traits entered without selections for a reference type I believe. It's very likely somebody else also fixed that error, I could probably just manually remove those edited lines.

**Comment by mjfreese** [comment]
> Can you elaborate on the Warlord Issues? There's a very good chance it's the same reference issue that somehow got added to the GST (and has been fixed), but I'd like to be sure.

Honestly very likely you fixed this already in #2153

**Comment by mjfreese** [comment]
@UrsinePatriarch I have cleaned up the weird incidental changes here so merging our 2 changesets should be nice and smooth

**Pull request merged**
