### PR TITLE
Knights as Lords of War for Legiones Astartes.

### PR DESCRIPTION
**Pull request by capitaladot**
Hey guys, mind taking a look and merging this?

### CODE REVIEW

**Comment by capitaladot** [comment]
Closes #818

**Comment by zopha** [comment]
Prophyrion is not a LoW for the Legions. Mechicum and Questoris only.

Are the rest only in the War Machine LoW detachment for LA?

**Comment by zopha** [comment]
I deleted the catalogue files on my tablet and put these in.

Questoris army
Roster has errors on load - http://i.imgur.com/Uf0lg01.png
No Knight armours available for house hold ranks - http://i.imgur.com/zUHdf0K.png

Legions and solar aux
Only available in a war machine detachment. Can they be taken singularly? Otherwise they look fine.

General
Prophyrion is available for all Armies. It should be LoW for mechicium and questoris, and an armour choice for Knight ranks.

**Comment by alphalas** [comment]
I would assume they can be taken singularly?

**Comment by capitaladot** [comment]
You need to import the GST to clear the. errors. I will fix the Porphyron.

War Machine Detachment allows 1-2 selections and doesn't confer other
rules, so do we need two sets of links?

**Comment by zopha** [comment]
I pulled in the zip file from the branch and deleted the local files on my tablet before copying the new ones in so they're the current ones. I just got some time at lunch to have a look, tested with files pulled in by GIT and the ZIP download from the branch. The Questoris file has duplicate ID's for the Aucteller in the GST.  If I remove the entry in the GST it works, since it's a Knight Rank it should only be in the Questoris file.

As for the missing armours the link from each household ranks points to an empty SSEG.

2017-03-07 13_11_24-data editor 2 00 14 - questoris knight crusade army

**Comment by capitaladot** [comment]
In re: LoW, unless d this changed in b7:

The Acastus Knight Porphyrion
may be taken as a Lords of War
choice in a Mechanicum Taghmata
or Knights Questoris army.

**Comment by capitaladot** [comment]
So, end game the Porphyron is just t missing from Mechanicum. Will fix.

**Comment by zopha** [comment]
Also the Titans seem to have doubled up.

2017-03-07 19_17_03-data editor 2 00 14 - warhammer 30 000 - the horus heresy

**Comment by zopha** [comment]
Questoris is working now. Most of it looks good to me.

The Castellax and Vorax should be hidden unless Draykavac is selected as a HQ but that's a minor list issue.

**Comment by capitaladot** [comment]
Thanks for the cleanup. I had it in progress, but didn't quite get it
sorted over lunch before your push showed up.

**Comment by zopha** [comment]
Fixes #771 #592

**Comment by capitaladot** [comment]
Found a bug in this... Porphyrion is not a Questoris rank option, simply a Lord of War.

**Pull request merged**
