### PR TITLE
Knight Dominus and Armigers

### PR DESCRIPTION
**Pull request by Mayegelt**
Changes

Added the Questoris Knight Dominus Horus Heresy.gst file as a lord of war for all armies without Blessed Autosimulacra

Added the Questoris Knight Dominus to Questoris Knight.cat as an armour variant for all current ranks of knights and Blessed Autosimulacra

Added Scion Auxilia with Questoris Knight Armiger to Questoris Knight.cat as non-compulsory troops, with Implacable Advance

Added Questoris Knight Armiger to Mechanicum - Tahmata Army List.cat as a 0-1 Heavy Support choice, without Implacable Advance

## Test Case
https://drive.google.com/open?id=1QHlWgj_n1bZo-14Ru0TjrcSEdg5sWP6s link to test file. Can't see any issues from my end.

### CODE REVIEW

**Comment by Mayegelt** [comment]
Corrected issue that Thundercoil Harpoon lacked rule, and Shieldbreaker missiles lacked stats and rule.

**Comment by thebiggeordiegeek** [comment]
Seems good to me

**Comment by Mayegelt** [comment]
Just added Custodes Venatari #1470 
Have tested the other files more on my phone and my local gaming club and it has worked for #1468 #1467

**Comment by thebiggeordiegeek** [comment]
Working fine for me, looks good to go.

**Pull request merged**
