### PR TITLE
RoW update for Tsons

### PR DESCRIPTION
**Pull request by Arkangelmark5**
The Guard Of The Crimson King
Added restrictions for Allied Detachments
Added Sehkmet to troops
Added constraints for Magnus, Amon and Ahriman

The Achaean Configuration
Added constraints for Techmarine Covenant and Praevian
Added Castellax-Achea to Troops

## Not done yet
Constraint for the various praetors as the Astartes Legion file can't share information from the Tsons Cat.
One workaround is to move Magnus, Amon and Ahriman to the main Astartes Legion Cat

### CODE REVIEW

**Comment by Mayegelt** [comment]
Haven't had a good look at the request. Kinda busy today and tomorrow. But seeing your to-do list. Here is my solution. I think it has been done for a couple of other universal RoW.

The Praetor / Magnus / Ahriman constraint can be made inside LA file.
Create a new Category in LA. Then have a modifier in all 5 of the units that adds the category to that unit if that RoW and if they are satisfying the requirement.
Have the category with a min in force of 0. Modifier with set min to 1 if that RoW is in force.

**Comment by Arkangelmark5** [comment]
Updated The Guard Of The Crimson King Compulsory HQs. Everything should be working across both Rites now

**Comment by Arkangelmark5** [comment]
Also fixed issues from https://github.com/BSData/horus-heresy/issues/2650#issue-1495665282, though they aren't technically Tson issues. 
Also added Scout/Infiltrate special rules to the vigilator

**Comment by Mayegelt** [comment]
Had to make a few fixes to the pull request, so redid what was needed, but couldn't make a pull request to your branch/fork for some reason.

1) Currently it is enforcing that every centurion needs to be a praevian instead of just 1 per force.
2) it is also asking for Court of the Crimson King ROW requirements to be fulfilled in every force, not just crimson king. 
3) Castellax-Achea if taken as elites, are requiring more than 1. This should only be for troops.

**Pull request closed without merging**
