### PR TITLE
FAQ + Playtest rules, Various fixes and updates. Added Qin Xa and Raldoron

### PR DESCRIPTION
**Pull request by Mayegelt**
Issues from #1472 resolved

I fixed Armillus Dynat & Autilon Skorr not starting with Artificer Armour

I have changed Power Glaive to stats to S User/+1

Redid the selections for power weapons to stop terminator command squads from taking Power Glaives. 

Added Nemean Reaver Master Crafted Bolt Pistol.

Qin Xa and Raldaron Added

### CODE REVIEW

**Comment by Mayegelt** [comment]
Added all FAQ and Playtest rules.
Playtest rules are accessable as a selection from Force Org (like HQ, Troops...)

**Comment by capitaladot** [comment]
@Mayegelt can you rebase these as separate PRs? This is way too much to test at once.

**Comment by thebiggeordiegeek** [comment]
Can’t find any issues with these myself, other than the lightning claw on the Sgt in Destroyers being free when it should be 10pts, but that’s an easy fix.

**Comment by Mayegelt** [comment]
@capitaladot I could try to pull the thing apart, but it would be an absolute pain in the arse to do so as things like the Playtest rules stuff in some cases go with the non playtest stuff, and of course having put in a bit for playtest rules in of course affects all the playtest bits.

I have a few friends in the local group for me who have downloaded my version off my dropbox and no issues seem to be emerging outside of the couple of issues of Pts values (that have now been fixed as reported). But anything else can be sorted after i think.

Issue i guess is that as this was a big change i wanted to get as much done in 1 night as i could, as i have an upcoming tourney to go to, and was "in the zone" for doing something. Not sure how to split up into small sections, each as their own request. Especially as when i was making it, i started doing it 1 way, then switched as i found a better one part way through.

**Comment by capitaladot** [comment]
@Mayegelt merged this, but let's try to keep separate things separate going forward.

**Comment by capitaladot** [comment]
@Mayegelt I had to back this out, as it destroyed hours of work in the Centurion power weapons, and replaced tons of complicated show hide rules with incorrect show hide rules that were only applied to the Herald.

**Pull request merged**
