### PR TITLE
Update 2022 - LA - Thousand Sons.cat

### PR DESCRIPTION
**Pull request by anthonylerpiniere**
## Fixed Units
Amend points cost for Khenetai Occult Blademaster Meltabombs from 5 to 10

### Related Issues

* closes # [3113](https://github.com/BSData/horus-heresy/issues/3113)

### CODE REVIEW

**Comment by anthonylerpiniere** [comment]
I have no idea - I tried it twice and had the same result.  I've only updated the value for the meltabombs using Data Editor.  Something to do with the version of BattleScribe I have installed (2.03.21)?

**Comment by anthonylerpiniere** [comment]
Saved in NR Editor and pushed changes.  The numerical changes have been sorted.  It looks like some of the other  elements have moved around in the file, but the values look to be the same.  The game system revision has been increased to 100 which isn't something I changed in the editor so not sure if that's a problem or not.

**Comment by nstephenh** [comment]
> The game system revision has been increased to 100 which isn't something I changed in the editor so not sure if that's a problem or not.

Game system revision auto-updates from the revision number of the game system. That's fine.

**Review by nstephenh — APPROVED** [review]
While the other stuff moving around is annoying, it's probably just because the thousand sons cat hasn't been edited in a while and newrecruit has likely made changes to the saving code.

**Pull request merged**
