### PR TITLE
Dark Angels RoW & Hexagrammaton restrictions

### PR DESCRIPTION
**Pull request by reilly-cuauhtemoc-8178**
## Added Units

- Added a Centurion (Storm of War) unit with only wargear and Hexagrammaton options for use with the Storm of War RoW.
- Added alternative versions for their respective FoC slots of the Kratos Squadron, Predator Squadron, Mortalis Destroyer Squad, Destroyer Assault Squad, Interemptor Squad, Assault Squad, Despoiler Squad, Tactical Squad, Tartaros Terminator Squad, Cataphractii Terminator Squad, Veteran Squad, Outrider Squad, Sky-Hunter Squad, and Seeker Squad for the various RoWs.

### Other changes

- Added warlord and unit restrictions for the Hexagrammaton types for the various RoWs.
- Added Dedicated Transports for the Steel Fist RoW.

### Related Issues

Related Horus Heresy 2.0 Tracking #2070 

## Not done yet

- Some illegal Dedicated Transport options (mostly the Rhino in squads larger than 10) are still available.
- Seeker's Arrow "Non-Fast/Skimmer/Flyer" restriction not yet implemented.
- Various special rules (Line, Heart of the Legion, etc.) applied by RoWs are not yet implemented.

### Issues
- Was unable to implement the Storm of War restriction on Compulsory Troop squad size (compulsory troops must always take maximum number of models) without forcing all "Compulsory Troops" not actually filling the Compulsory role to also take the full size. 

### Images
Images highlighting features.

### Steel Fist:
steel_fist

### Eskaton Imperative:
eskaton_imperative_must_be_dreadwing

### Storm of War:
storm_of_war

### Unbroken Vow:
unbroken_vow_must_be_deathwing

### Seeker's Arrow:
seekers_arrow

### Serpent's Bane:
serpents_bane_must_be_firewing

### CODE REVIEW

**Comment by UrsinePatriarch** [comment]
Well well, mate; seems like you've been busy with this.
I'll take a good long look at this tomorrow to double-check everything, but this sure seems up to snuff at a glance.
Are you in the Discord for any questions?

**Comment by alphalas** [comment]
For future reference; PLEASE DO NOT make big changes like this without talking to us first on the discord

**Comment by reilly-cuauhtemoc-8178** [comment]
Ah, I wasn't aware there was a Discord, but I'll make sure to check it out tomorrow.

**Comment by Mayegelt** [comment]
From what i can see this looks good.

**Pull request merged**
