### PR TITLE
#1665 & #1670 & #1671

### PR DESCRIPTION
**Pull request by Mayegelt**
Had to reduce the cost of Primus Nullificator  Consul upgrade by 35pts as the Consul has Cata armour by default and the way the armour gets its value seemed unable to then be modified by the consul being taken. So the reduction has had to be factored in on the consul itself to balance it out.

### CODE REVIEW

**Comment by Mayegelt** [comment]
Another new weapon for the Arquitor

Also noticed that for some reason i'd put side armour as only 11, it should have been 12. Might be the older sheet had lower armour, or i may have made a mistake.

**Comment by capitaladot** [comment]
> Had to reduce the cost of the Consul upgrade by 35pts as the Consul has Cata armour by default and the way the armour gets its value seemed unable to then be modified by the consul being taken. So the reduction has had to be factored in on the consul itself to balance it out.

It had at one time been set to 0 then modified, but someone re-did it.

What consul gets free Cataphractii?

**Comment by Mayegelt** [comment]
Just the Primus Nullificator. @capitaladot

**Comment by Mayegelt** [comment]
#1661 added. Fixed issue for Sacrificial offering.

**Comment by Mayegelt** [comment]
Power Lances for Command Squads added.

**Comment by Mayegelt** [comment]
Fixed the Dread / Comtemptor / Cortus. Previously by swapping your ranged weapon for a melee one, it was giving you the bonus attack, even if you then swapped the melee one you started with for a ranged one.
Also relinked Meltagun on a few things, as it was once again doubled up for no reason.
Also added a profile to Heavy Bolter with Suspensor Web.

**Comment by Mayegelt** [comment]
Had forgot to add the GST file upgrade for Heavy Bolter in the upload.

**Pull request merged**
