### PR TITLE
Lots of Mechy Goodness

### PR DESCRIPTION
**Pull request by Mayegelt**
**Added**
Added a Knights and Titans Profile type
Added Fast Vehicle Catagory with sub rule of Flat Out

**Warhound, Reaver, Nemisis and Warlord Titans** to Titans all selectable in all lists.
All appropriate stuff also added for them as well.
Decompiled the Missile launcher into a single entry, rather than entry with sub entries within it.

**Reasons for adding** 
Photon Gauntlet - to GST ADDED as Shared Selection Entry as it is shared with Mech and Titans
Castellax Battle-automata Maniples - to GST for Praevian & Brethren of Iron (ROW) [gains 5+ It Will not Die] & Head of the Gorgon (IH ROW)
Vorax Battle-automata Maniples - to GST for Brethren of Iron & Praevian
Domitar Battle-automata Maniples - to GST for Brethren of Iron
Thanatar Siege-automata Maniple - to GST for Brethren of Iron (Max 1)

**Cybernetica** type ADDED as Category with Rule
Paragon of Metal ADDED as Shared Selection Entry

**Castellax STUFF** - ADDED as Shared Selection Entry
Shock Chargers ADDED as Shared Selection Entry
Mauler Bolt Cannon ADDED as Shared Selection Entry
Darkfire Cannon ADDED as Shared Selection Entry
Siege Wrecker ADDED as Shared Selection Entry
Power Blade Array ADDED as Shared Selection Entry
Maxima Bolter ADDED as Shared Selection Entry

**Vorax STUFF** -  ADDED as Shared Selection Entry
Power Blade Array ADDED as Shared Selection Entry
Lightning Gun ADDED as Shared Selection Entry
Irad Cleanser ADDED as Shared Selection Entry

**Domitar STUFF** - ADDED as Shared Selection Entry
Graviton Hammers ADDED as Shared Selection Entry

**Thanatar STUFF** -  ADDED as Shared Selection Entry
Shock Chargers ADDED as Shared Selection Entry
Graviton Ram ADDED as Shared Selection Entry
Plasma Mortar ADDED as Shared Selection Entry
Sollex Heavy-Las ADDED as Shared Selection Entry
Twin-linked Mauler Bolt Cannon ADDED as Shared Selection Entry
Thanatar Maniple ADDED in Thanatar

### CODE REVIEW

**Comment by Mayegelt** [comment]
I've left root links out of the Thanatar, Vorax, Castellax and Domitar, bit you can re-add to check then remove after if you need.

**Comment by Mayegelt** [comment]
This was started prior to a couple of other changes to GST which has some Dark Angels, Emperors Children, White Scars & Spacewolf changes.

**Comment by Mayegelt** [comment]
TAGE 2
Disruption ADDED TO GST (used mainly in Titans but also somewhere else for Arc Blaster)
Placeholder Knights ADDED to Knight Catalogue along with Household Ranks and a way to hide them when shared.
Heavy Stubber ADDED to GST
Ion Gauntlet Shield ADDED to GST (used in Questoris and Mech)
Ion Shield ADDED to GST (used in Questoris and Mech)
Ionic Deflector ADDED to GST (used in Questoris and Mech)
Flank Speed rule ADDED to GST (used in Questoris and Mech)
Karacnos Mortar Battery ADDED to GST (used in Questoris and Mech)
Multi-laser (used in Questoris and Mech and likely in others)
Catastrophic Explosion ADDED to GST
Catastrophic Destuction ADDED to GST
Overtaxed Reactor ADDED to GST
Phased Plasma-Fusil ADDED to GST
Lightning Cannon ADDED to GST

Added Knights
Acastus Knight Porphyrion
Armiger Helverin Talon
Armiger Warglaive Talon
Knight Acheron
Knight Castigator
Knight Lancer
Knight Questoris
Questoris Acastus Knight Asterius
Questoris Knight Atrapos
Questoris Knight Magaera
Questoris Knight Styrix

All of these once catalogue is linked should show up on LA, & Mech as LoW. with the exception of the Armigers that aren't meant to.

**Comment by Mayegelt** [comment]
Moved a bunch of the things I'd put in GST into Mech Library.
Added Triaros Dedicated transport to Mech library and linked to be dedicated transport for Secutarii units

Titans and Questoris should now been 100% active and working.

**Review by UrsinePatriarch — APPROVED** [review]
Seems like my commit didn't break everything, thank God.
Seems good otherwise, mate.

**Pull request closed without merging**
