### PR TITLE
Da row fixes

### LINKED ISSUE #2603: Bug report: 2022 - LA - Dark Angels.cat
File: 2022 - LA - Dark Angels.cat

BattleScribe version: 2.03.21

Platform: Desktop

Dropbox: No

Description: Selecting a Spartan as a DT for a unit in the Steel Fist RoW throws an error after a Hexagrammaton type is selected.

### PR DESCRIPTION
**Pull request by reilly-cuauhtemoc-8178**
# DA RoW Fixes

## Added Units
- Added compulsory versions of Troops choices for Storm of War.

## Fixed Units
- Added RoW special rules to various units (Heart of the Legion in Unbroken Vow, Rampage and Outflank in Seeker's Arrow, Stubborn in Storm of War).
- Fixed an issue where Infiltrate appeared on all Troops even if they didn't have the upgrade from Serpent's Bane.
- Fixed an issue where units weren't allowed to select a Spartan dedicated transports in the Steel Fist RoW.
- Fixed Seeker's Arrow restrictions on Heavy Support.
- Also added "Cavalry" type to Proteus Land Speeders and "Heavy" type to Javelin Speeders.

### Related Issues
Continued from #2503
Closes #2603

## Test Case

Seeker's Arrow: Independent Characters with the Cavalry sub-type have Rampage(2).
da_seekers_arrow_1

Ravenwing Infantry and Cavalry units have Outflank.
da_seekers_arrow_2

Serpent's Bane: Infiltrate toggle now correctly limits at 3.
da_serpents_bane

Steel Fist: Troops can take appropriate Dedicated Transports.
da_steel_fist

Storm of War: Compulsory Troops must be at maximum size, can take a special Centurion.
da_stormwing

The Unbroken Vow: Terminators and Veterans have Heart of the Legion.
da_unbroken_vow

### CODE REVIEW

**Comment by Mayegelt** [comment]
Sorry I'm awful at looking over other people's commits.
Is this one based on the live release, pre-release or my pull request?

**Comment by reilly-cuauhtemoc-8178** [comment]
It should be up to date with master, I just wasn't sure which branch to merge it to. 

Yeah, I just looked and I'm not sure what the deal is with the changes, since I only modified the LA, DA, and HH.gst files.

**Comment by Mayegelt** [comment]
I think it's likely as you merged from master after the start.
What might be an idea is don't delete the branch you are on. But start a new one and put the files into that. That will then only show actual changes

**Comment by reilly-cuauhtemoc-8178** [comment]
Ah, okay, that sounds good.

**Comment by alphalas** [comment]
@reilly-cuauhtemoc-8178 would you happen to be on the BSData discord? if so please ping me in HH data

**Pull request closed without merging**
