### PR TITLE
Legion Praetor update

### PR DESCRIPTION
**Pull request by zopha**
I've done work on the Legion Praetor to make all of it's items linked entries and set up its profile to change depending on what wargear is added. I've added the armour types I know about, "Aether, Mantel of Ultramar, standard Terminiator armour, etc"

Frost weapons haven't been added, unless someone else has done it already. I'll try to get that done in a little while when I have a list of legion-specific equipment IC's can take.

A review of it would be appreciated in case I've missed/broken anything before it's merged.

### CODE REVIEW

**Comment by capitaladot** [comment]
Nice, will review

**Comment by zopha** [comment]
Conflicts now. Will need to reimplement.

**Comment by capitaladot** [comment]
Make a pull request, and fix the conflicts?

**Comment by capitaladot** [comment]
Checked out, will get it worked out.

**Comment by zopha** [comment]
Lazyness due to lack of understanding so it really leads to more work.

I added a good few shared entries for the Praetor and entries got added to all the LA units for Army of Dark Compliance so I'm not sure if this will be an easy thing or something that will take a few hours to figure outl.

**Pull request closed without merging**
